### ISSUE TITLE
Add another sorting algorithm

### ISSUE THREAD

**Issue by jordanhilado** [jordanhilado/Algorithm-Visualizer#1]
Check out the code and implement another sorting algorithm to the application.

**Comment by ravidyarev** [comment]
Please assign this issue to me.

**Comment by jordanhilado** [comment]
Done @ravidyarev

**Comment by StephenTrainor** [comment]
Do you mind if I attempt at adding radix sort?

**Comment by TusharSharmaIN** [comment]
Please check @jordanhilado, selection sort is added. PR #2, 😊

**Comment by ravidyarev** [comment]
thank you @jordanhilado

**Comment by jordanhilado** [comment]
Go ahead @StephenTrainor

**Comment by Isha2208** [comment]
Can I add heap sort algorithm in C language or is it necessary for the language to be python

**Comment by jordanhilado** [comment]
You're free to use any language, just as long as it runs perfectly and there are no issues. Although you are going to need to implement some python into sortingAlgs.py in order for the algorithm to run. @Isha2208

**Comment by Isha2208** [comment]
can I add heap sort in python

**Comment by jordanhilado** [comment]
Go ahead @Isha2208
